class YusufOSError extends Error {
  constructor(code, message, { status = 400, details = {} } = {}) {
    super(message);
    this.name = "YusufOSError";
    this.code = code;
    this.status = status;
    this.details = details;
  }
}

const ErrorCodes = Object.freeze({
  POLICY_DENIED: "POLICY_DENIED",
  ACTION_FORBIDDEN: "ACTION_FORBIDDEN",
  APPROVAL_REQUIRED: "APPROVAL_REQUIRED",
  APPROVAL_INVALIDATED: "APPROVAL_INVALIDATED",
  APPROVAL_EXPIRED: "APPROVAL_EXPIRED",
  APPROVAL_ALREADY_DECIDED: "APPROVAL_ALREADY_DECIDED",
  INTENT_VERSION_CONFLICT: "INTENT_VERSION_CONFLICT",
  RESOURCE_CHANGED: "RESOURCE_CHANGED",
  MUTATIONS_DISABLED: "MUTATIONS_DISABLED",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
  UNAUTHORIZED: "UNAUTHORIZED",
  LOCALHOST_REQUIRED: "LOCALHOST_REQUIRED",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  EXECUTION_UNKNOWN: "EXECUTION_UNKNOWN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  MODEL_UNAVAILABLE: "MODEL_UNAVAILABLE",
});

module.exports = { YusufOSError, ErrorCodes };
