const PRINCIPAL_TYPES = Object.freeze({
  USER: "USER",
  AGENT: "AGENT",
  SCHEDULE: "SCHEDULE",
  SYSTEM: "SYSTEM",
});

const TASK_STATUSES = Object.freeze({
  PLANNED: "PLANNED",
  READY: "READY",
  RUNNING: "RUNNING",
  BLOCKED: "BLOCKED",
  WAITING_APPROVAL: "WAITING_APPROVAL",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
});

const RUN_STATUSES = Object.freeze({
  QUEUED: "QUEUED",
  RUNNING: "RUNNING",
  WAITING_APPROVAL: "WAITING_APPROVAL",
  WAITING_DEPENDENCY: "WAITING_DEPENDENCY",
  BLOCKED: "BLOCKED",
  VERIFYING: "VERIFYING",
  FAILED: "FAILED",
  FAILED_UNKNOWN: "FAILED_UNKNOWN",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
});

const INTENT_STATUSES = Object.freeze({
  INTENT_CREATED: "INTENT_CREATED",
  POLICY_EVALUATED: "POLICY_EVALUATED",
  POLICY_DENIED: "POLICY_DENIED",
  FORBIDDEN: "FORBIDDEN",
  WAITING_APPROVAL: "WAITING_APPROVAL",
  AUTHORIZED: "AUTHORIZED",
  EXECUTING: "EXECUTING",
  EXECUTED_UNVERIFIED: "EXECUTED_UNVERIFIED",
  VERIFIED: "VERIFIED",
  FAILED: "FAILED",
  FAILED_UNKNOWN: "FAILED_UNKNOWN",
  INVALIDATED: "INVALIDATED",
  CANCELLED: "CANCELLED",
});

const APPROVAL_STATUSES = Object.freeze({
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
  INVALIDATED: "INVALIDATED",
  CONSUMED: "CONSUMED",
});

const POLICY_OUTCOMES = Object.freeze({
  ALLOW: "ALLOW",
  REQUIRE_APPROVAL: "REQUIRE_APPROVAL",
  DENY: "DENY",
  FORBIDDEN: "FORBIDDEN",
});

const RISK_LEVELS = Object.freeze({
  L0: "L0",
  L1: "L1",
  L2: "L2",
  L3: "L3",
  L4: "L4",
});

const SECURITY_SETTING_KEYS = Object.freeze({
  EXTERNAL_MUTATIONS_DISABLED: "EXTERNAL_MUTATIONS_DISABLED",
});

module.exports = {
  PRINCIPAL_TYPES,
  TASK_STATUSES,
  RUN_STATUSES,
  INTENT_STATUSES,
  APPROVAL_STATUSES,
  POLICY_OUTCOMES,
  RISK_LEVELS,
  SECURITY_SETTING_KEYS,
};
